package protocol

import (
	"fmt"
	"reflect"
	"slices"
	"sort"
	"strings"
)

// exported is the ordered list of Go types mirrored into TypeScript. Adding a
// type here (and running `make generate`) is the only way a new protocol type
// reaches the browser; TestTypeScriptInSync fails when the checked-in file
// drifts from this list.
var exported = []any{
	Attachment{},
	MessageItem{},
	ToolImage{},
	ToolActivity{},
	Transfer{},
	Notice{},
	Summary{},
	Item{},
	RejectionReason{},
	ToolConfirmationRequest{},
	ElicitationRequest{},
	QueuedMessage{},
	QueueStatus{},
	RunStatus{},
	Usage{},
	PermissionsView{},
	SessionMeta{},
	StoredSessionMeta{},
	StoredSession{},
	StoredSessionItems{},
	Snapshot{},
	Delta{},
	ItemRef{},
	ToolResolved{},
	ElicitResolved{},
	ChatClosed{},
	Event{},
	DashboardEvent{},
	Health{},
	WorkspaceHint{},
	Bootstrap{},
	PluginPage{},
	PluginEvent{},
	PluginConfiguration{},
	PluginMCPServer{},
	PluginFeatures{},
	Plugin{},
	ManagedPlugin{},
	PluginError{},
	PluginCatalog{},
	PluginManagementCatalog{},
	OpenWorkspaceRequest{},
	Workspace{},
	SessionSummary{},
	ExecutionLocationRequest{},
	ExecutionLocationRef{},
	CreateChatRequest{},
	ResumeChatRequest{},
	ChatRef{},
	SendMessageRequest{},
	Accepted{},
	ModelOption{},
	ToolOption{},
	UpdateToolRequest{},
	UpdateConfigRequest{},
	ChatOptions{},
	ToolConfirmationReply{},
	ElicitationReply{},
	RetitleRequest{},
	Stats{},
	CommandInfo{},
	APIError{},
}

// enums maps a named Go string type to its allowed literal values.
var enums = map[string][]string{
	"RunState":          {string(RunStateIdle), string(RunStateRunning), string(RunStateStopping)},
	"DeliveryMode":      {string(DeliveryNormal), string(DeliverySteer), string(DeliveryFollowUp)},
	"ToolState":         {string(ToolStatePending), string(ToolStateAwaiting), string(ToolStateRunning), string(ToolStateSuccess), string(ToolStateError), string(ToolStateRejected)},
	"NoticeLevel":       {string(NoticeInfo), string(NoticeWarning), string(NoticeError)},
	"ToolDecision":      {string(DecisionApprove), string(DecisionApproveAlways), string(DecisionReject)},
	"ElicitationAction": {string(ElicitAccept), string(ElicitDecline), string(ElicitCancel)},
	"ItemKind":          {string(ItemKindMessage), string(ItemKindTool), string(ItemKindTransfer), string(ItemKindNotice), string(ItemKindSummary)},
	"EventType": {
		string(EventSnapshot), string(EventRunStatus), string(EventMessageItem),
		string(EventAssistantDelta), string(EventAssistantEnd), string(EventReasoningDelta),
		string(EventReasoningEnd), string(EventToolStart), string(EventToolUpdate),
		string(EventToolEnd), string(EventToolConfirmation), string(EventToolResolved),
		string(EventElicitation), string(EventElicitResolved), string(EventTransfer),
		string(EventUsage), string(EventNotice), string(EventSummary), string(EventSessionMeta),
		string(EventGap), string(EventChatClosed),
	},
	"DashboardEventType": {
		string(DashboardEventSnapshot), string(DashboardEventSessionsChanged),
		string(DashboardEventPluginsChanged), string(DashboardEventGap),
	},
}

func tsType(t reflect.Type) string {
	if name := t.Name(); name != "" {
		if _, ok := enums[name]; ok {
			return name
		}
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem()) + " | null"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return "Array<" + strings.TrimSuffix(tsType(t.Elem()), " | null") + ">"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key()), tsType(t.Elem()))
	case reflect.Struct:
		return t.Name()
	case reflect.Interface:
		return "unknown"
	default:
		return "unknown"
	}
}

// GenerateTypeScript renders the browser-side mirror of this package.
func GenerateTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by `make generate` (internal/protocol/tsgen.go). DO NOT EDIT.\n")
	b.WriteString("// Regenerate after changing internal/protocol/types.go; `make typecheck` fails on drift.\n\n")

	names := make([]string, 0, len(enums))
	for n := range enums {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		quoted := make([]string, 0, len(enums[n]))
		for _, v := range enums[n] {
			quoted = append(quoted, "'"+v+"'")
		}
		fmt.Fprintf(&b, "export type %s = %s;\n", n, strings.Join(quoted, " | "))
	}
	b.WriteString("\n")

	for _, v := range exported {
		t := reflect.TypeOf(v)
		fmt.Fprintf(&b, "export interface %s {\n", t.Name())
		for f := range t.Fields() {
			if !f.IsExported() {
				continue
			}
			tag := f.Tag.Get("json")
			if tag == "-" {
				continue
			}
			parts := strings.Split(tag, ",")
			name := parts[0]
			if name == "" {
				name = f.Name
			}
			optional := len(parts) > 1 && slicesContains(parts[1:], "omitempty")
			ts := tsType(f.Type)
			// Go emits `null` for nil slices/maps, so widen them.
			switch f.Type.Kind() {
			case reflect.Slice, reflect.Map:
				ts += " | null"
			}
			q := ""
			if optional {
				q = "?"
				ts = strings.TrimSuffix(ts, " | null")
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", name, q, ts)
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func slicesContains(s []string, v string) bool {
	return slices.Contains(s, v)
}
