// Code generated by `make generate` (internal/protocol/tsgen.go). DO NOT EDIT.
// Regenerate after changing internal/protocol/types.go; `make typecheck` fails on drift.

export type DashboardEventType = 'snapshot' | 'sessions_changed' | 'plugins_changed' | 'gap';
export type DeliveryMode = 'normal' | 'steer' | 'followUp';
export type ElicitationAction = 'accept' | 'decline' | 'cancel';
export type EventType = 'snapshot' | 'run_status' | 'message_item' | 'assistant_delta' | 'assistant_end' | 'reasoning_delta' | 'reasoning_end' | 'tool_start' | 'tool_update' | 'tool_end' | 'tool_confirmation' | 'tool_confirmation_resolved' | 'elicitation' | 'elicitation_resolved' | 'transfer' | 'usage' | 'notice' | 'summary' | 'session_meta' | 'gap' | 'chat_closed';
export type ItemKind = 'message' | 'tool' | 'transfer' | 'notice' | 'summary';
export type NoticeLevel = 'info' | 'warning' | 'error';
export type RunState = 'idle' | 'running' | 'stopping';
export type ToolDecision = 'approve' | 'approveAlways' | 'reject';
export type ToolState = 'pending' | 'awaiting_confirmation' | 'running' | 'success' | 'error' | 'rejected';

export interface MessageItem {
  id: string;
  role: string;
  agentName: string;
  text: string;
  reasoning: string;
  streaming: boolean;
  createdAt: string;
  model: string;
  cost?: number;
  inputTokens?: number;
  outputTokens?: number;
  cachedInputTokens?: number;
  cacheWriteTokens?: number;
  reasoningTokens?: number;
}

export interface ToolImage {
  name: string;
  mimeType: string;
  data: string;
}

export interface ToolActivity {
  id: string;
  name: string;
  displayName?: string;
  category: string;
  agentName: string;
  argsSummary: string;
  arguments?: Record<string, unknown>;
  images?: Array<ToolImage>;
  state: ToolState;
  preview: string;
  truncated: boolean;
  outputBytes: number;
  isError: boolean;
}

export interface Transfer {
  id: string;
  fromAgent: string;
  toAgent: string;
  switching: boolean;
}

export interface Notice {
  id: string;
  level: NoticeLevel;
  message: string;
  code: string;
}

export interface Summary {
  id: string;
  text: string;
  cost: number;
}

export interface Item {
  kind: ItemKind;
  message?: MessageItem;
  tool?: ToolActivity;
  transfer?: Transfer;
  notice?: Notice;
  summary?: Summary;
}

export interface RejectionReason {
  label: string;
  reason: string;
}

export interface ToolConfirmationRequest {
  toolCallId: string;
  toolName: string;
  displayName?: string;
  agentName: string;
  argsSummary: string;
  pattern: string;
  patternLabel: string;
  metadata?: Record<string, string>;
  rejectionReasons: Array<RejectionReason> | null;
}

export interface ElicitationRequest {
  elicitationId: string;
  message: string;
  mode: string;
  url: string;
  agentName: string;
  schema?: unknown;
}

export interface QueuedMessage {
  id: string;
  text: string;
}

export interface QueueStatus {
  steerDepth: number;
  steerCapacity: number;
  followUpDepth: number;
  followUpCapacity: number;
  steer: Array<QueuedMessage> | null;
  followUps: Array<QueuedMessage> | null;
}

export interface RunStatus {
  state: RunState;
  runId: string;
  queue: QueueStatus;
}

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  cost: number;
  contextLimit: number;
}

export interface PermissionsView {
  allow: Array<string> | null;
  ask: Array<string> | null;
  deny: Array<string> | null;
  agentsIgnore: boolean;
  sessionGrants: Array<string> | null;
}

export interface SessionMeta {
  chatId: string;
  sessionId: string;
  title: string;
  workspaceId: string;
  workingDir: string;
  agentName: string;
  model: string;
  thinkingLevel: string;
  thinkingLevels: Array<string> | null;
  permissions: PermissionsView;
  createdAt: string;
}

export interface Snapshot {
  seq: number;
  meta: SessionMeta;
  items: Array<Item> | null;
  run: RunStatus;
  usage: Usage;
  pendingConfirmations: Array<ToolConfirmationRequest> | null;
  pendingElicitations: Array<ElicitationRequest> | null;
}

export interface Delta {
  itemId: string;
  text: string;
}

export interface ItemRef {
  itemId: string;
}

export interface ToolResolved {
  toolCallId: string;
  decision: ToolDecision;
  pattern: string;
}

export interface ElicitResolved {
  elicitationId: string;
}

export interface ChatClosed {
  reason: string;
}

export interface Event {
  type: EventType;
  seq: number;
  snapshot?: Snapshot;
  run?: RunStatus;
  message?: MessageItem;
  delta?: Delta;
  ref?: ItemRef;
  tool?: ToolActivity;
  confirmation?: ToolConfirmationRequest;
  toolResolved?: ToolResolved;
  elicitation?: ElicitationRequest;
  elicitResolved?: ElicitResolved;
  transfer?: Transfer;
  usage?: Usage;
  notice?: Notice;
  summary?: Summary;
  meta?: SessionMeta;
  closed?: ChatClosed;
}

export interface DashboardEvent {
  type: DashboardEventType;
  seq: number;
  workspaceIds?: Array<string>;
  sessionIds?: Array<string>;
  reason?: string;
  revision?: string;
}

export interface Health {
  status: string;
  uptimeSeconds: number;
}

export interface WorkspaceHint {
  path: string;
  label: string;
}

export interface Bootstrap {
  appVersion: string;
  agentVersion: string;
  agentCommit: string;
  configDir: string;
  dataDir: string;
  cacheDir: string;
  sessionDb: string;
  pluginDir: string;
  csrfToken: string;
  sandboxed: boolean;
  modelsAvailable: boolean;
  modelsHint: string;
  workspaceHints: Array<WorkspaceHint> | null;
  notices: Array<Notice> | null;
}

export interface PluginPage {
  id: string;
  path: string;
  label: string;
  sidebar: boolean;
}

export interface Plugin {
  apiVersion: number;
  id: string;
  name: string;
  description: string;
  version: string;
  fingerprint: string;
  entryUrl: string;
  styleUrl?: string;
  pages: Array<PluginPage> | null;
}

export interface PluginError {
  pluginId?: string;
  message: string;
}

export interface PluginCatalog {
  plugins: Array<Plugin> | null;
  errors: Array<PluginError> | null;
}

export interface OpenWorkspaceRequest {
  path: string;
}

export interface Workspace {
  workspaceId: string;
  path: string;
  label: string;
  notices: Array<Notice> | null;
  agentsMd: boolean;
  agentsIgnore: boolean;
}

export interface SessionSummary {
  sessionId: string;
  title: string;
  workingDir: string;
  createdAt: string;
  messages: number;
  live: boolean;
  chatId?: string;
  runState?: RunState;
}

export interface CreateChatRequest {
  workspaceId: string;
}

export interface ResumeChatRequest {
  workspaceId: string;
  sessionId: string;
}

export interface ChatRef {
  chatId: string;
  sessionId: string;
}

export interface SendMessageRequest {
  text: string;
  mode: DeliveryMode;
}

export interface Accepted {
  accepted: boolean;
  mode: DeliveryMode;
  runId: string;
  queued: boolean;
}

export interface ModelOption {
  name: string;
  ref: string;
  provider: string;
  model: string;
  family: string;
  contextLimit: number;
  inputCost: number;
  outputCost: number;
  isCurrent: boolean;
  isDefault: boolean;
  isCustom: boolean;
  isCatalog: boolean;
}

export interface UpdateConfigRequest {
  model?: string;
  thinkingLevel?: string;
}

export interface ToolConfirmationReply {
  toolCallId: string;
  decision: ToolDecision;
  reason: string;
}

export interface ElicitationReply {
  elicitationId: string;
  action: ElicitationAction;
  content?: Record<string, unknown>;
}

export interface RetitleRequest {
  title: string;
}

export interface Stats {
  usage: Usage;
  messages: number;
  toolCalls: number;
  model: string;
  agentName: string;
  durationSeconds: number;
}

export interface CommandInfo {
  name: string;
  description: string;
  kind: string;
}

export interface APIError {
  error: string;
  code: string;
  details?: string;
}

